export default {
    "numberOfSupplier":0,
    "supplier":[
        {
            "name":"name1",
            "supplier":"supplier1",
            "supplierPart":"",
            "availableIn":"availableIn",
            "price":222.0,
            "currency":"currency",
            "shipTo":"shipTo",
            "sourcingSpoc":"sourcingSpoc",
            "materialCode":"materialCode",
            "additionalCharges":"additionalCharges"
        },
        {
            "name":"name2",
            "supplier":"supplier1",
            "supplierPart":"",
            "availableIn":"availableIn",
            "price":222.0,
            "currency":"currency",
            "shipTo":"shipTo",
            "sourcingSpoc":"sourcingSpoc",
            "materialCode":"materialCode",
            "additionalCharges":"additionalCharges"
        },
        {
            "name":"name3",
            "supplier":"supplier2",
            "supplierPart":"",
            "availableIn":"availableIn",
            "price":222.0,
            "currency":"currency",
            "shipTo":"shipTo",
            "sourcingSpoc":"sourcingSpoc",
            "materialCode":"materialCode",
            "additionalCharges":"additionalCharges"
        }
    ],
    "responseCode":"200",
    "processedSupplier":"1",
    "exceptionList":[]
}