export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_DONE = "API_CALL_DONE";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const CLEAR_INPUT_FIELDS = "CLEAR_INPUT_FIELDS";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const SUPPLIER_CALL_DONE = "SUPPLIER_CALL_DONE";
export const FILTER_CHANGE = "FILTER_CHANGE";
export const SEARCH_CALL_DONE = "SEARCH_CALL_DONE";
